### PR TITLE
Upgrade identityserver4 to 4.1.1

### PR DESCRIPTION
**Pull request by GreenShadeZhang**
Upgrade identityserver4 to 4.1.1, update the database context migration file, after my test, normal use.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnContainers?pullRequest=1617) <br/>All CLA requirements met.

**Comment by HighRobot42** [comment]
"Sorry, there was an error : invalid_scope" while trying to authorize a swagger project

Identity Logs (here I take basket but it is the same for the other projects):

[23:43:37 INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeEndpoint for /connect/authorize

[23:43:37 ERR] Scope basket not found in store.

[23:43:37 ERR] Request validation failed

**Comment by sughosneo** [comment]
Hi @GreenShadeZhang , thank you for submitting this PR.

Did a quick test in local and could see following error for the WebSPA and WebMVC. Could you please check at your end ?

**WebSPA**

image

**WebMVC**

image


Thank you @HighRobot42 for pointing it out.

**Comment by GreenShadeZhang** [comment]
> Hi @GreenShadeZhang , thank you for submitting this PR.
> 
> Did a quick test in local and could see following error for the WebSPA and WebMVC. Could you please check at your end ?
> 
> **WebSPA**
> 
> image
> 
> **WebMVC**
> 
> image
> 
> Thank you @HighRobot42 for pointing it out.

identityserver4 mainly uses apiscope so when I initialized the apiscope invalid_scope error disappeared, invalid_request was because the mvc client RequestPkce default value was true, but the mvc redirect login page did not bring the required parameters, when I chose to set it to false, the request was normal, But I'm not sure if the mvc project matches the authentication service, and I may need to modify the mvc project if necessary.

**Comment by GreenShadeZhang** [comment]
> "Sorry, there was an error : invalid_scope" while trying to authorize a swagger project
> 
> Identity Logs (here I take basket but it is the same for the other projects):
> 
> [23:43:37 INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeEndpoint for /connect/authorize
> 
> [23:43:37 ERR] Scope basket not found in store.
> 
> [23:43:37 ERR] Request validation failed

Thank you @HighRobot42  for pointing it out.

You can use the latest code test

**Comment by HighRobot42** [comment]
I can't get the authorization within the basket swagger ui with your solution. After login, it does not redirect me to the consent html page. Controllers return 401.

**Comment by GreenShadeZhang** [comment]
> I can't get the authorization within the basket swagger ui with your solution. After login, it does not redirect me to the consent html page. Controllers return 401.

Can you provide specific information? For example, which client id you used for the test, or provide me with a link to sample code for testing.

**Comment by HighRobot42** [comment]
I have just added to the swagger clients the property RequireConsent = true in the Config.cs The default value for this property in the class Client has switched from true to false with the recent update. 
Otherwise the solution remains the same as yours and when I try a basket controller i get  "www-authenticate: Bearer error="invalid_token"error_description="The audience 'empty' is invalid"

**Comment by HighRobot42** [comment]
I finally solved it this way:

In basket client config (Config.cs in Identity solution) I have set the three following properties:
`
                    RequireConsent = true,
                    IncludeJwtId = false,
                    RequirePkce = false,`

Helped by this post from Stackoverflow 
[https://stackoverflow.com/questions/61814688/how-to-add-an-aud-claim-to-access-token](url)

I have updated the basket Startup.cs with the following lines (property TokenValidationParameters)
```

private void ConfigureAuthService(IServiceCollection services)
        {
            // prevent from mapping "sub" claim to nameidentifier.
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Remove("sub");

            var identityUrl = Configuration.GetValue<string>("IdentityUrl");

            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;

            }).AddJwtBearer(options =>
            {
                options.Authority = identityUrl;
                options.RequireHttpsMetadata = false;
                options.Audience = "basket";

                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateAudience = false
                };

            });
        }

```

Controllers now return 200 for the basket swagger ui. Let me know what you think about my modifications. The above parameters also have to be updated the same way in the other solutions.

**Comment by GreenShadeZhang** [comment]
> I finally solved it this way:
> 
> In basket client config (Config.cs in Identity solution) I have set the three following properties:
> ` RequireConsent = true, IncludeJwtId = false, RequirePkce = false,`
> 
> Helped by this post from Stackoverflow
> [https://stackoverflow.com/questions/61814688/how-to-add-an-aud-claim-to-access-token](url)
> 
> I have updated the basket Startup.cs with the following lines (property TokenValidationParameters)
> 
> ```
> 
> private void ConfigureAuthService(IServiceCollection services)
>         {
>             // prevent from mapping "sub" claim to nameidentifier.
>             JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Remove("sub");
> 
>             var identityUrl = Configuration.GetValue<string>("IdentityUrl");
> 
>             services.AddAuthentication(options =>
>             {
>                 options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
>                 options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
> 
>             }).AddJwtBearer(options =>
>             {
>                 options.Authority = identityUrl;
>                 options.RequireHttpsMetadata = false;
>                 options.Audience = "basket";
> 
>                 options.TokenValidationParameters = new TokenValidationParameters
>                 {
>                     ValidateAudience = false
>                 };
> 
>             });
>         }
> ```
> 
> Controllers now return 200 for the basket swagger ui. Let me know what you think about my modifications. The above parameters also have to be updated the same way in the other solutions.

I feel that your configuration can be simplified. The configuration in the demo demo of identityserver4.x is relatively simplified, and you should use the implicit mode to configure swagger. You can refer to the official demo to use.

https://github.com/IdentityServer/IdentityServer4/tree/main/samples/Quickstarts

**Comment by HighRobot42** [comment]
All right but have you tested your own solution? They have changed some default values in the Client class that you have not taken into account. I m not really sure I understand your point btw.

**Review by KamranShahid — APPROVED** [review]

**Comment by GreenShadeZhang** [comment]
Identityserver3 and identityserver4 are a bit different, so some projects need to adjust the way of authentication use, I adjusted the normal function of webmvc, for different clients also need to adjust the corresponding adjustment, this needs to be tested and modified for the project. I dealt with the main conflict, the overall project should be able to run, I hope that after testing can merge branches, and then further development, to ensure the integrity of the whole.
QQ截图20220605164042

**Comment by velosojose** [comment]
عزيزي قمران شهيد
و
شكرًا لتفهمك ، كنت أبحث عن شخص بهذا الاسم. لقد دفعتني للاتصال بك ومعرفة أفضل السبل التي يمكننا من خلالها مساعدة بعضنا البعض. أنا السيد خوسيه فيلوسو ، الذي أعمل كمدير تدقيق هنا في البنك الوطني للفلبين. أعتقد أن إرادة الله أن ألتقي بك الآن. لديّ مناقشة عمل مهمة أريد مشاركتها معك ، والتي أعتقد أنها ستثير اهتمامك لأنها تتعلق باسمك الأخير وستستفيد منها.
مواطن من بلدك يُدعى الجنطيانا الشهيد ، لديه وديعة ثابتة في بنكي ، بقيمة 12.500.000.00 دولار أمريكي (اثنا عشر مليونًا وخمسمائة ألف دولار أمريكي) كان تاريخ انتهاء هذه الوديعة العام الماضي. لسوء الحظ ، كان الشهيد الجنطاني من بين ضحايا حادث 11 مايو 2012 المميت في الفلبين والذي شارك فيه سبع سيارات على طول الطريق المؤدي إلى مدينة باراناكي مانيلا بالفلبين ، حيث قتل 35 شخصًا على الفور.

لم تكن إدارة البنك الذي أتعامل معه على علم بوفاته حتى الآن ، فقد علمت بذلك لأنه كان صديقي وكنت كاتب حساباته عندما تم فتح الحساب قبل ترقيتي. ومع ذلك ، لم يذكر السيد الجنطيان أي أقارب / ورثة عند فتح الحساب ولم يكن متزوجًا وليس لديه أطفال. طلبت مني إدارة البنك التي أتعامل معها الأسبوع الماضي إعطاء تعليمات بشأن ما يجب فعله بشأن أموالها إذا قمت بتجديد العقد.

**Comment by velosojose** [comment]
أعلم أن هذا سيحدث وهذا هو السبب في أنني طلبت أداة للتعامل مع الموقف لأنه إذا علم مديرو البنوك التي أتعامل معها أن الجنطيان قد مات وليس له ورثة ، فسيحصلون على الأموال لاستخدامه بشكل شخصي. لذلك لا أريد أن يحدث ذلك. لهذا السبب عندما رأيت اسمك كنت سعيدًا والآن أطلب تعاونك لتقديمك كقريب / وريث للحساب لأنك تحمل نفس اللقب ، وسيقوم المقر الرئيسي للبنك بإصدار الحساب لك. لا يوجد أي خطر. سيتم تنفيذ الصفقة بموجب اتفاقية مشروعة تحميك من أي خرق للقانون.

إن طلب المال أفضل من السماح لمديري البنوك بأخذه ، فهم أثرياء بالفعل. أنا لست شخصًا جشعًا ، لذا أقترح أن نتشارك الأموال بالتساوي ، 50/50٪ لكلا الطرفين ، وستساعدني حصتي في فتح شركتي الخاصة واستخدام العائدات في الأعمال الخيرية ، وهو ما كان حلمي.

قل لي رأيك في اقتراحي. يرجى التعامل مع هذه المعلومات على أنها سرية ، ولدي المزيد لأكتبه لك للحصول على التفاصيل بعد تلقي ردك العاجل بدقة عبر عنوان بريدي الإلكتروني الشخصي: joseveloso0017@gmail.com
اتمنى لك نهارا سعيدا وبارك الله عليه. توقع استجابتك العاجلة

**Comment by velosojose** [comment]
مرحبًا
السيد خوسيه فيلوسو

**Comment by velosojose** [comment]
joseveloso0017@gmail.com

**Comment by GreenShadeZhang** [comment]
Can this pr be merged?

**Comment by erjain** [comment]
IdentityServer4 has been upgraded to Duende IdentityServer 6.2 via PR: https://github.com/dotnet-architecture/eShopOnContainers/pull/2012. This PR can be closed now.

**Pull request closed without merging**
