### PR TITLE
Service Bus persisted connection for ISubscriptionClient

### PR DESCRIPTION
**Pull request by Marusyk**
Added SubscriptionClient  to ServiceBusPersisterConnection to make the same behavior as TopicClient 

https://github.com/dotnet-architecture/eShopOnContainers/blob/1b7200791931f33c94206822a69644ca820bb0dc/src/BuildingBlocks/EventBus/EventBusServiceBus/DefaultServiceBusPersisterConnection.cs#L27-L35

Issue  #1519

Please review,
Thank you in advance

### CODE REVIEW

**Comment by sughosneo** [comment]
Hi @Marusyk , thank you for submitting this PR. We have recently updated our `dev` branch to `.NET 5`. 
Could you please update this PR ? 

Thank you.

**Comment by Marusyk** [comment]
@sughosneo done

**Comment by Marusyk** [comment]
@sughosneo any chance to merge it before new conflicts?

**Review by sughosneo — APPROVED** [review]
Hi @Marusyk , thank you for updating this PR.
Tested these changes with `docker-compose`. LGTM ! Merging the changes with `dev` branch.

**Pull request merged**
