### PR TITLE
Seeking feedback: Build and run on .Net 6 preview 6

### PR DESCRIPTION
**Pull request by JcolemanNR**
It's probably premature to merge this, but I am seeking feedback on my attempt to upgrade eShopOnContainers to .NET 6 preview 6. 

I work for New Relic and we are using eShopOnContainers as a validation tool for our compatibility with .NET 6.

I was able to get everything working via docker-compose on CLI on windows. The only thing I wasn't able to upgrade to .Net 6 was the WebStatus app which experiences a strange issue with a Linq .Any() command throwing an error about multiple results being returned when upgraded to .Net 6??? I was getting similar issues in other services and upgrading the NuGet references for EF seemed to solve it, but not for the WebStatus project.

I'm interested in collaborating on upgrading this project to .NET 6. I upgraded ALL the NuGet packages at first and found some huge issues with the changes to the IdentityServer API. I'm sure there are other challenging tasks like this where you want to upgrade to the latest and greatest versions across this whole stack.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnContainers?pullRequest=1734) <br/>All CLA requirements met.

**Comment by sughosneo** [comment]
Hi @JcolemanNR, thank you for submitting this PR and showing interest in contributing. Overall, it looks great to me. 👍 

Right now, the `dev` branch supports `.NET 5` and would continue to do so till `.NET 6` goes to GA, and we have successfully migrated all the components of `eShop` applications to `.NET 6`. So, we won't be able to merge these changes directly with the `dev` branch yet.

But Having said that, these changes are valuable and surely a great foundation for everyone to refer and help updating the remaining components/packages to `.NET 6`. I have created a feature branch [migration/net-6](https://github.com/dotnet-architecture/eShopOnContainers/tree/migration/net-6), for all of us to refer the `.NET 6` related latest changes. If you could redirect your PR to this specific branch, we will merge the changes in there and refer it for the future modifications.

CC: @nishanil

**Comment by JcolemanNR** [comment]
@sughosneo: Re-targeted to the migration feature branch, and pinned some .net sdk images that I missed to Preview 6 to prevent unexpected errors every time a new nightly version comes out.

Thanks for taking a look!

**Review by sughosneo — APPROVED** [review]
Thank you @JcolemanNR , build succeeds. 
Will merge the changes with the feature branch `migration/net-6`

**Pull request merged**
