### PR TITLE
.net core 2.0 packages update and some warnings fixed

### PR DESCRIPTION
**Pull request by SychevIgor**
https://github.com/aspnet/EntityFrameworkCore/issues/8923#issuecomment-310431600

https://github.com/aspnet/EntityFrameworkCore/issues/9129

https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/4bc89022f1e1e0d314a0dda57db829e51b4963df/ChangeLog.md autoack
https://www.nuget.org/packages/FluentValidation.Mvc6/ mvc 6 must be changed to FluentValidation.AspNetCore
https://github.com/aspnet/Security/issues/1310 auth in moq changed

### CODE REVIEW

**Comment by SychevIgor** [comment]
@CESARDELATORRE I know, that your team working on the migration, and I hope that can speedup this process. I can guarantee that code can be build, we don't have warning (except in test projects)

**Comment by CESARDELATORRE** [comment]
@Sychevlgor. We really appreciate your work and collaboration!. But in this specific case, we're currently in the middle of the migration to .NET Core 2, so a few things in the PR might be currently duplicated so we cannot accept this PR.
However, a few points in this PR were taken into account anyways, too, so, thanks a lot! :)

**Comment by SychevIgor** [comment]
@CESARDELATORRE  Sure, I just split my PR on parts.  https://github.com/dotnet-architecture/eShopOnContainers/pull/299

**Comment by fbpw** [comment]
Close if comleate

**Pull request closed without merging**
