### PR TITLE
Updating nuget packages and scripts

### PR DESCRIPTION
**Pull request by josephwambura**
Updating nuget packages and scripts: and fix serilog errors

### CODE REVIEW

**Comment by erjain** [comment]
Hi @josephwambura, Thank you so much for your contribution. It will be really helpful. Due to some recent commits, there is a conflict in this PR, can you resolve it and update the changes? We'll review it and take it forward.

**Comment by josephwambura** [comment]
Hiello @erjain . I have resolved the conflicts.

**Comment by josephwambura** [comment]
> Hi @josephwambura, Thank you so much for your contribution. It will be really helpful. Due to some recent commits, there is a conflict in this PR, can you resolve it and update the changes? We'll review it and take it forward.

Is it okay on your side now?

**Comment by erjain** [comment]
Hi @josephwambura, the docker-compose build is causing the issue, can you recheck and fix the build?

**Pull request closed without merging**
