### PR TITLE
Modernization

### PR DESCRIPTION
**Pull request by ReubenBond**
This is a joint effort between @davidfowl & myself to modernize and clean up eShop.
There is more to do, but we wanted to merge what we have so far before we continue.

@erjain, we have tested this locally in VS (launch & manually test + automated tests) and via docker compose, but we haven't tested beyond that (Kubernetes, Azure). I don't expect you to review this because the PR is far too large, but if you could run some of your own tests, that would be greatly appreciated.

Addresses #2070

### CODE REVIEW

**Comment by erjain** [comment]
This is great work, you guys nailed it. I'll review and test it.

**Comment by ReubenBond** [comment]
@erjain merge when ready

**Review by erjain — APPROVED** [review]
Looks good to me.

**Comment by markheath** [comment]
I think this update means that logs are no longer appearing in Seq. Is this intentional? There still is a Seq container in `docker-compose.yml` but its not picking anything up

**Comment by davidfowl** [comment]
Yes it’s intentional. We’re also not done with the clean up. This was just the first big set of changes

**Pull request merged**
