### PR TITLE
Fix namespace for IdentityDb

### PR DESCRIPTION
**Pull request by slsniffer**
Since all other databases have prefix "Microsoft.eShopOnContainers.Services" we need to fix IdentityDb namespace as well.

### CODE REVIEW

**Comment by slsniffer** [comment]
@dotnet-policy-service agree

**Comment by SrushtiPasari94** [comment]
@slsniffer please update your forked branch with dotnet-architecture/eShopOnContainers, as its 14 commits behind.
I need to test your updated branch changes, so that we can merge the PR.

**Comment by slsniffer** [comment]
> @slsniffer please update your forked branch with dotnet-architecture/eShopOnContainers, as its 14 commits behind. I need to test your updated branch changes, so that we can merge the PR.
@SrushtiPasari94 I've updated forked branch

**Review by SrushtiPasari94 — APPROVED** [review]

**Comment by SrushtiPasari94** [comment]
Tested the changes on docker desktop, working fine with the namespace fix for identityDb

**Pull request merged**
