### PR TITLE
Added EventBus.Tests to solution

### LINKED ISSUE #1683: The EventBus.Tests project isn't added to the solution
The EventBus.Tests project still exist in the directory but isn't added to the solution. 
It also still has Standard2.1 as its target framework and doesn't build as a result

Was this project meant to be removed or should it be included in the project?

### PR DESCRIPTION
**Pull request by sanderobdeijn**
- Added EventBus.Tests to solution
- Updated targetframework to net5.0
- Consolidated nuget packages

Fixes #1683

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnContainers?pullRequest=1684) <br/>All CLA requirements met.

**Comment by sughosneo** [comment]
Hi @sanderobdeijn , thank you for submitting this PR. Will review and update.

**Comment by sughosneo** [comment]
Could you please fix the `docker-compose build` step? You'll have to include the newly added project in all the docker files.

**Review by sughosneo — APPROVED** [review]
Tested the changes in local. LGTM! Will merge the changes.

**Pull request merged**
